### PR TITLE
docs: Create asset summaries investigation

### PR DESCRIPTION
**Pull request by l0b0**
Investigation into creating asset summaries - looks like it's actually pretty simple.

You can try the notebook yourself by running `nix-shell --run 'jupyter lab extensions/linz/notebooks/asset-datetime-summary.ipynb'`. It's my first notebook, so be gentle :)

### CODE REVIEW

**Comment by dwsilk** [comment]
Relevant to the suggestion posted in this comment: https://github.com/radiantearth/stac-spec/issues/1153#issuecomment-963640804. Discussion ongoing.

**Comment by l0b0** [comment]
@dwsilk Should I close this, or do we want to keep the investigation?

**Comment by billgeo** [comment]
Is this something we would merge @l0b0 or should it just be closed as having served its purpose?

**Comment by l0b0** [comment]
> Is this something we would merge @l0b0 or should it just be closed as having served its purpose?

It doesn't need to be merged, but it might serve as a useful example of such an investigation for future ones.

**Review by billgeo — APPROVED** [review]
Worked for me.

**Review by MitchellPaff — APPROVED** [review]

**Pull request merged**
