### PR TITLE
fix(historical Imagery): allow null values in proj:epsg summary

### PR DESCRIPTION
**Pull request by MDavidson17**

### CODE REVIEW

**Review by amfage — APPROVED** [review]
:thumbsup:

**Comment by billgeo** [comment]
Hi @MDavidson17. @l0b0 is away this week, but myself or @MitchellPaff can probably review this if that helps? It looks good to me. :)

**Comment by MDavidson17** [comment]
> Hi @MDavidson17. @l0b0 is away this week, but myself or @MitchellPaff can probably review this if that helps? It looks good to me. :)

Awesome thanks, @billgeo, I'll add you both. A very small change but there was a bit of chat about null values in this [PR](https://github.com/linz/stac/pull/191) so I thought I'd give a wide review on our decision :+1:

**Comment by billgeo** [comment]
> > Hi @MDavidson17. @l0b0 is away this week, but myself or @MitchellPaff can probably review this if that helps? It looks good to me. :)
> 
> Awesome thanks, @billgeo, I'll add you both. A very small change but there was a bit of chat about null values in this [PR](https://github.com/linz/stac/pull/191) so I thought I'd give a wide review on our decision 👍

Null is valid in the projection extension, and proj:epsg is required for items so I guess you have to be able to specify a null value? If we want to question that should probably do it upstream?

https://github.com/stac-extensions/projection/blob/7f1d1c9db7c33dba0944972a983d74fd480d4c62/json-schema/schema.json#L25-L26

**Review by billgeo — APPROVED** [review]
LGTM

**Comment by billgeo** [comment]
Although do you need to update the README and examples?

**Pull request merged**
